#ifndef _MIHYPLATFORM_PCH_H_
#define _MIHYPLATFORM_PCH_H_

#include "MIHYCommonHeader.h"

#include "MIHYPlatform_API.h"

#if defined(MIHYPLATFORM_IMPORT)
    #define MIHYPLATFORM_API MIHYPLATFORM_LIBRARY_SYMBOL_IMPORT_COMMAND
#else
    #define MIHYPLATFORM_API MIHYPLATFORM_LIBRARY_SYMBOL_EXPORT_COMMAND
#endif

#endif